name: Build Java Natives (MacOS)
inputs:
  build_type:
    required: true
    default: Release
  arch:
    required: true
    default: x64
  cmake_osx_arch:
    required: true
    default: x86_64

runs:
  using: composite
  steps:
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Native build cache
      uses: actions/cache@v4
      with:
        path: bindings/java/native/build/cmake
        key: native-build-${{ runner.os }}-${{ matrix.arch }}-${{ hashFiles('**/CMakeLists.txt') }}

    - name: Execute Gradle build
      working-directory: bindings/java
      env:
        BUILD_TYPE: ${{ inputs.build_type }}
        BUILD_ARCH: ${{ inputs.arch }}
        CMAKE_OSX_ARCHITECTURES: ${{ inputs.cmake_osx_arch }}
      run: ./gradlew :native:build
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: natives-${{ runner.os }}-${{ matrix.arch }}
        path: bindings/java/native/build/libs/
